### ISSUE TITLE
Create client library

### ISSUE THREAD

**Issue by mburns-acom** [spring-guides/gs-circuit-breaker#1]
This is really more of a usage question.
I've been trying to figure out a way to package service client code into a jar that can be included in multiple apps (and include the circuit-breaker functionality shown here). Is this possible? It feels like this would be very challenging or impossible.

**Comment by gregturn** [comment]
In essence, https://github.com/spring-guides/gs-circuit-breaker/blob/master/complete/reading/src/main/java/hello/BookService.java IS the client code you are looking for. This guide is setup as both a client and a service, and "reading" is the client.

I'm going to presume you are asking, "how can I put the same @Service code into all my various clients that talk to this common backend?"

In that regards, you can write a single module that contains this service. Then import that module into all of your clients, and they will all have this service, designed to talk to the backend.

**Comment by gregturn** [comment]
The critical component to build a hystrix service is...

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-hystrix</artifactId>
		</dependency>
```

**Comment by mburns-acom** [comment]
You presume correctly. When you say "import that module" do you believe this is possible at the compiled jar level or must I import the java client code? I was having trouble building a client jar (that could be used by multiple client apps), so I paused to evaluate what I was trying to do.

**Comment by gregturn** [comment]
You can create a module called my-reading-client that contains spring-cloud-starter-hystrix, defines an @Service, and makes RestTemplate calls wrapped with @HystrixCommand. You could techically publish your artifact to maven central, and any code that wants to use this service, could do so by declaring "my-reading-client" as a dependency.

**Comment by mburns-acom** [comment]
Thanks. I'll press on in that direction.
