### ISSUE TITLE
Update client code to inject RestTemplate

### ISSUE THREAD

**Issue by gregturn** [spring-guides/gs-circuit-breaker#2]
Right now, the RestTemplate is created on the spot. It would be better to inject it via constructor autowiring.

Are you game for that @fifthposition?

**Comment by fifthposition** [comment]
Sure thing. 😃

**Comment by fifthposition** [comment]
Mis-tagged the commit. https://github.com/spring-guides/gs-circuit-breaker/commit/d803fd6dc23a38fed9dc04c26d542f7d3e5e24fa
