### ISSUE TITLE
Link problem

### ISSUE THREAD

**Issue by Avec112** [spring-guides/gs-circuit-breaker#6]
Seems the README.adoc shows github raw link references instead of the actual content. Its all over the page. 

![spring-guides gs-circuit-breaker circuit breaker learn how to degrade gracefully services using hystrix 2016-09-20 09-27-35](https://cloud.githubusercontent.com/assets/5219735/18679465/8d0abda2-7f14-11e6-9408-d4f9bd2860f6.jpg)

**Comment by dsyer** [comment]
That's expected. Github cannot render the links, but they are rendered in the app: https://spring.io/guides/gs/circuit-breaker/.

**Comment by fifthposition** [comment]
These are rendered correctly on the spring.io website: spring.io/guides/gs/circuit-breaker

GitHub apparently does not render them.

**Comment by Avec112** [comment]
Aha. Thanks.
