### ISSUE TITLE
new trigger type

### ISSUE THREAD

**Issue by masoudsafa** [spring-guides/gs-circuit-breaker#7]
Hi 
I was wondering if you can add some thing to your project. I have multiple web service calls and i don't want to add an alternative method for all of them. can you add capability of throwing custom Exception instead of calling alternative method. Exception can be global or given as annotation input.

Best Regards.

**Comment by ryanjbaxter** [comment]
Please ask your question in the [Spring Cloud Netflix project](https://github.com/spring-cloud/spring-cloud-netflix).

**Comment by masoudsafa** [comment]
thanks
